### ISSUE TITLE
希望提供一份 cloud.json 的示例

### ISSUE THREAD

**Issue by Little-LinNian** [daizihan233/KuoHuBit#17]
<!--
请在下一行开始描述你的提问/建议/反馈
--
希望提供 cloud.json 的示例，用以完成自搭建机器人

**Comment by daizihan233** [comment]
``` json
{
  "QCloud_Secret_id": "",
  "QCloud_Secret_key": "",
  "MySQL_Pwd": "",
  "MySQL_Port": 3306,
  "MySQL_Host": "localhost",
  "MySQL_db": "datebase",
  "Redis_Host": "localhost",
  "Redis_port": 6379
}
```
| 名称                | 类型     | 意义                           | 示例        |
|-------------------|--------|------------------------------|-----------|
| QCloud_Secret_id  | string | 腾讯云 SecretID（以后更新会用，目前不填也可）  |           |
| QCloud_Secret_key | string | 腾讯云 SecretKey（以后更新会用，目前不填也可） |           |
| MySQL_Pwd         | string | MySQL 密码                     | password  |
| MySQL_Port        | int    | MySQL 端口                     | 3306      |
| MySQL_Host        | string | MySQL 地址                     | localhost |
| MySQL_db          | string | MySQL 数据库名称                  | database  |
| Redis_Host        | string | Redis 地址                     | localhost |
| Redis_port        | int    | Redis 端口                     | 6379      |

__**注意：大小写敏感，且所有的key均没有对应的value，如果您需要对此仓库二次开发时，请不要上传此文件**__

**Comment by ltzXiaoYanMo** [comment]
@daizihan233 你是一个一个一个（？）
