### ISSUE TITLE
[Request]: 群聊日志

### ISSUE THREAD

**Issue by hakuzousu666** [daizihan233/KuoHuBit#21]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能名称

记录成员加入时间

### 新功能描述

例えば：
我：`@某人 加入信息`
BOT：`这个人的QQ 加入时间`
某只狐狸奇奇怪怪的小想法

### 来点色图

任何色图终将绳之以法，和蔼！

**Comment by daizihan233** [comment]
我提个想法：
让机器人尽可能地记录群日志，包括但不限于入群、退群、改名、禁言等等
然后用信息来查找相关数据
这个的话排列组合比较多，我就不在 Issue 里列举了
到时候做出了看文档吧（

**Comment by hakuzousu666** [comment]
えっ？还有个文件上传(搓手手)
```go
fmt.Println("😃")
```

**Comment by daizihan233** [comment]
啊你说什么文件上传（

**Comment by hakuzousu666** [comment]
这个构思用伪代码表达如下
```go
if userevent == file update{
    fmt.Println(user,"上传了一个群文件")
   }
```

**Comment by daizihan233** [comment]
啊 懂了

**Comment by ltzXiaoYanMo** [comment]
想法很不错，但是在 QQ Mobile Version 9 已经加入了此文件，故不做此更新
