### ISSUE TITLE
[Request]: 没有建议（bushi

### ISSUE THREAD

**Issue by ltzXiaoYanMo** [daizihan233/KuoHuBit#23]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能名称

和6一样，可以添加一个c（或草）的检测（

### 新功能描述

这有什么可表述的（

### 来点色图

任何色图终将绳之以法，和蔼！
![3D7594274A831142AF51BE6400E090E4](https://github.com/daizihan233/KuoHuBit/assets/115706851/a2dd6bd5-2cbf-4ee1-a1e6-1c61a0fade30)

**Comment by daizihan233** [comment]
写了跟没写一样（

**Comment by ltzXiaoYanMo** [comment]
草

**Comment by ltzXiaoYanMo** [comment]
你什么意思？（

**Comment by Emerald-AM9** [comment]
6
