### ISSUE TITLE
[Bug?]: 当机器人检测到6时有时没有报错但无法发送图片

### ISSUE THREAD

**Issue by ltzXiaoYanMo** [daizihan233/KuoHuBit#31]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有解决方案。
- [X] 我已熟读并背诵[文档](https://bot.khbit.cn)。

### 重现步骤

当你重启Bot的时候，数据库（也就是no_6的表）并没有这个群号（uid）出现，但是在群中并没有回复图片。（在之前并没有人扣6）在<del>mian.py</del>main.py中没有任何提示，Mirai Main Qsign都未停止

<del>这到底怎么出来的我也不知道，看命罢</del>

### 期望的结果是什么？

看看能不能修复，修不了就算了（？）

### 实际的结果是什么？

main/mirai中没有风控提示等其他七七八八的sb错误，但是就是发不出来图（悲）

### 来点色图

任何色图终将绳之以法，和蔼！
![803663A02289D18B502CACEBB6FD45CD](https://github.com/daizihan233/KuoHuBit/assets/115706851/5e0792bc-249d-45cc-9175-a9b547da034b)

**Comment by daizihan233** [comment]
没日志我修不了一点（
等你下次运气好复现的时候把日志贴出来 **让我看看！**

**Comment by ltzXiaoYanMo** [comment]
![image](https://github.com/daizihan233/KuoHuBit/assets/115706851/3c23f049-bd86-427e-8d89-047e843c0674)

**Comment by daizihan233** [comment]
重启一下彳亍不彳亍？

**Comment by daizihan233** [comment]
6榜是否有相同bug存在？

**Comment by ltzXiaoYanMo** [comment]
![image](https://github.com/daizihan233/KuoHuBit/assets/115706851/5a9fce25-b738-4e6c-b104-67c9a759a287)

**Comment by ltzXiaoYanMo** [comment]
目前来说，可能事有的
