### ISSUE TITLE
[Request]: 

### ISSUE THREAD

**Issue by hakuzousu666** [daizihan233/KuoHuBit#32]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有此功能。
- [X] 我已熟读并背诵[文档](https://bot.khbit.cn)。

### 新功能名称

查看go模块下载趋势

### 新功能描述

我想在QQ群里通过[goproxycn](https://goproxy.cn) 的[状态页面](https://goproxy.cn/stats) 的API查看go模块的趋势

### 来点色图

任何色图终将绳之以法，和蔼！

**Comment by ltzXiaoYanMo** [comment]
你怎么天天go（
