### ISSUE TITLE
[Request]: 舍利子兑换

### ISSUE THREAD

**Issue by TKInvconry** [daizihan233/KuoHuBit#7]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述教程和 ["《提问的智慧》"](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/main/README-zh_CN.md)。
- [X] 我确定这不是因为操作失误而引起的问题。
- [X] 我确定这是一个有意义的Issue，且目前没有此功能。

### 新功能名称

舍利子兑换

### 新功能描述

可以通过 某些指令* 使用户消耗账户 功德* 兑换 舍利子*，舍利子* 不需要太多作用，这只是功德的一部分

**Comment by daizihan233** [comment]
与          一起      ，这是功德的一部分（不是
